# Generated by Django 4.0.3 on 2023-11-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartition',
            new_name='CartItem',
        ),
    ]
